#!/usr/bin/env bats
load helpers

# Declare the service
consul_service="consul"
address="$(dig +short ${consul_service})"
port="8500"

@test "Check 'ZK_HOST' configuration is correct when a 'zookeeper' service is registered in Consul" {

  # Register service (actually we just use the consul service and register with the name and tags we want)
  run register_service "zookeeper" "10.11.12.13" "2181"
  [ "$status" -eq 0 ]

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template /etc/consul-template/templates/solr.in.sh.ctmpl:/opt/solr/bin/solr.in.sh -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f /opt/solr/bin/solr.in.sh;echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the service registered
  status=$(grep "ZK_HOST=10.11.12.13:2181/solr" /opt/solr/bin/solr.in.sh 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]
}


@test "Check 'ZK_HOST' configuration is correct when multiple 'zookeeper' services are registered in Consul" {

  # Register a first zookeeper service (actually we just use the consul service and register with the name and tags we want)
  run register_service "zookeeper" "10.11.12.13" "2181"
  [ "$status" -eq 0 ]

  # Register a second zookeeper service (actually we just use the consul service and register with the name and tags we want)
  run register_service "zookeeper" "10.11.12.14" "2181"
  [ "$status" -eq 0 ]

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template /etc/consul-template/templates/solr.in.sh.ctmpl:/opt/solr/bin/solr.in.sh -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f /opt/solr/bin/solr.in.sh;echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the service registered
  status=$(grep "ZK_HOST=10.11.12.13:2181,10.11.12.14:2181/solr" /opt/solr/bin/solr.in.sh 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]
}
