#!/usr/bin/env bats
load helpers

# Declare the service
consul_service="consul"
address="$(dig +short ${consul_service})"
port="8500"

@test "Check 'ZK_HOST' configuration might be set in Consul" {

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template /etc/consul-template/templates/solr.in.sh.ctmpl:/opt/solr/bin/solr.in.sh -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f /opt/solr/bin/solr.in.sh;echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the service registered
  status=$(grep "ZK_HOST=\"zookeeper:2181/solr\"" /opt/solr/bin/solr.in.sh 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]

  # Change the configuration
  run register_key "service/solr/ZK_HOST" "zk:2181/solr"

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template /etc/consul-template/templates/solr.in.sh.ctmpl:/opt/solr/bin/solr.in.sh -once;echo $?)
  [ "$status" -eq 0 ]


  # Check the expected configuration has been generated by consul-template
  status=$(test -f /opt/solr/bin/solr.in.sh;echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the service registered
  status=$(grep "ZK_HOST=\"zk:2181/solr\"" /opt/solr/bin/solr.in.sh 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]

}